### PR TITLE
Add binding for G4MultiSensitiveDetector

### PR DESCRIPTION
**Pull request by bnara**
My model needed G4MultiSensitiveDetector.  I based this off the existing binding for G4MultiFunctionalDetector.

### CODE REVIEW

**Comment by HaarigerHarald** [comment]
Reading up on what this does now, I think this is for internal use only. When one passes multiple `G4VSensitiveDetector` to its `G4VUserDetectorConstruction` this will accommodate them automatically in a vector. Would you mind sharing how you intended to use it? And can you achieve a similar result by calling `SetSensitiveDetector` multiple times in a row with all `G4VSensitiveDetector`s you are planning to add to the logic volume?

**Comment by bnara** [comment]
Thanks for adding the iterator!

I am using `G4MultiSensitiveDetector` to effectively assign multiple instances of  `G4VSensitiveDetector` to a single `G4LogicalVolume`.

I don't believe the same result can be achieved by calling `SetSensitiveDetector` multiple times:
[G4LogicalVolume.cc#L478](https://gitlab.cern.ch/geant4/geant4/-/blame/geant4-11.3-release/source/geometry/management/src/G4LogicalVolume.cc#L478)

**Comment by HaarigerHarald** [comment]
Ahh I see, you are adding it manually to the `G4LogicalVolume` via its member function. While I think this method is the preferred way [G4VUserDetectorConstruction.cc#L217](https://gitlab.cern.ch/geant4/geant4/-/blob/geant4-11.3-release/source/run/src/G4VUserDetectorConstruction.cc#L217) and would automatically put multiple `G4VSensitiveDetector` in a `G4MultiSensitiveDetector`, I still think binding `G4MultiSensitiveDetector` might be useful when one tries to manipulate it later. Thanks

**Comment by bnara** [comment]
Thanks!  I didn't know about `G4VUserDetectorConstruction::SetSensitiveDetector()`.  In my model, I create and initialize the sensitive detectors at a later stage following geometry construction, so I ended up directly using `G4MultiSensitiveDetector`.

**Pull request merged**
